apiVersion: v1
kind: Service
metadata:
  name: {{ template "orchestrator.fullname" . }}
  labels:
    app: {{ template "orchestrator.name" . }}
    chart: {{ template "orchestrator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: orchestrator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "orchestrator.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orchestrator-sm
  labels:
    prometheus: monitoring
    app: {{ template "orchestrator.name" . }}
    chart: {{ template "orchestrator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: orchestrator
  endpoints:
  - port: http