apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bidder-sm
  labels:
    prometheus: monitoring
spec:
  selector:
    matchLabels:
      component: bidder
  endpoints:
  - port: http
