apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ad-content-pvc
  namespace: lucent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1000Gi