apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "System": "Warning",
          "Microsoft": "Warning"
        }
      },
      "ContentPath":"{{ .Values.content.path }}",
      "ContentHost":"{{ .Values.content.host }}",
      "ContentCache":"{{ .Values.content.cache }}",
      "AllowedHosts": "*",
      "media":{
        "ffmpegpath":"/opt/ffmpeg/bin/ffmpeg"
      },
      "ldap": {
        "host": "openldap-service.lucent.svc",
        "issecured": true,
        "port": 636
      },
      "ldap_mgmt": {
        "administrator": "{{ .Values.openldap.user }}",
        "credentials": "{{ .Values.openldap.password }}",
        "domain": "{{ .Values.openldap.domain }}",
        "clusters": {
          "secondary" : {
            "user": "{{ .Values.rabbitmq.user }}",
            "credentials": "{{ .Values.rabbitmq.password }}",
            "host": "{{ .Values.rabbitmq.secondaryHost }}"
          }
        }
      },
      "rabbit": {
        "host": "rabbitmq.lucent.svc",
        "user": "{{ .Values.rabbitmq.user }}",
        "credentials": "{{ .Values.rabbitmq.password }}",
        {{- if .Values.rabbitmq.secondaryHost }}
        "clusters": {
          "secondary" : {
            "user": "{{ .Values.rabbitmq.user }}",
            "credentials": "{{ .Values.rabbitmq.password }}",
            "host": "{{ .Values.rabbitmq.secondaryHost }}"
          }
        }
        {{- else }}
        "clusters": {}
        {{- end }}
      },
      "cassandra": {
        "endpoint": "cassandra.lucent.svc",
        "user": "{{ default "test" .Values.cassandra.user }}",
        "credentials": "{{ default "test" .Values.cassandra.password }}",
        "keyspace": "{{ default "portal" .Values.cassandra.keyspace }}",
        "format": "{{ default "PROTOBUF" .Values.cassandra.format }}"
      }
    }
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: {{ template "portal.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "portal.name" . }}
        release: {{ .Release.Name }}
        component: portal
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
    {{- with .Values.hostAlias }}
      hostAliases:
{{ toYaml . | indent 6 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-ec"
            - |
              echo "Getting configuration"
              cp /etc/config/*.json ./

              echo "Starting the portal"
              dotnet Portal.dll
          volumeMounts:
            - mountPath: /etc/config
              name: app-config
            - mountPath: /mnt/contents
              name: ad-contents
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: app-config
          configMap:
            name: portal-config
        - name: ad-contents
          persistentVolumeClaim:
            claimName: ad-content-pvc
