replicaCount: 1

image:
  repository: telefrek/lucent-bidder
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: 
  limits:
   memory: 2Gi
   cpu: 2
  requests:
   memory: 512Mi
   cpu: 1

hostAlias: {}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpression:
          - key: component
            operator: In
            values:
            - bidder
        topologyKey: kubernetes.io/hostname
