apiVersion: v1
kind: ConfigMap
metadata:
  name: content-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information"
        }
      },
      "ContentPath":"{{ .Values.content.path }}",
      "AllowedHosts": "*"
    }
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "content.fullname" . }}
  labels:
    app: {{ template "content.name" . }}
    chart: {{ template "content.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: {{ template "content.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "content.name" . }}
        release: {{ .Release.Name }}
        component: content
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
    {{- with .Values.hostAlias }}
      hostAliases:
{{ toYaml . | indent 6 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-ec"
            - |
              echo "Getting configuration"
              cp /etc/config/*.json ./

              echo "Starting the content server"
              dotnet ContentServer.dll
          volumeMounts:
            - mountPath: /etc/config
              name: app-config
            - mountPath: /mnt/contents
              name: ad-contents
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: app-config
          configMap:
            name: content-config
        - name: ad-contents
          persistentVolumeClaim:
            claimName: ad-content-pvc
